### PR TITLE
deps: upgrade ios/android sdk dependencies TA-7176

### PR DESCRIPTION
**Pull request by douglaseggleton**
Upgrading to the latest version of the SDKs to get support for push payments.

Moved to TA-7176

### CODE REVIEW

**Comment by luca-gr4vy** [comment]
@douglaseggleton can't check with the example app at the moment as the build fails for some reasons 😫 have you checked yourself? I remember it was failing when testing yesterday due to the `cart_items` object having changed in the new version (so we have to pass another couple of properties now)

**Comment by douglaseggleton** [comment]
> @douglaseggleton can't check with the example app at the moment as the build fails for some reasons 😫 have you checked yourself? I remember it was failing when testing yesterday due to the `cart_items` object having changed in the new version (so we have to pass another couple of properties now)

@luca-gr4vy Can you slack me the build error? I had an issues with the latest upgrade is iOS 17 that I had to get around. I managed to get it working locally in the end to run through a couple of transactions.

**Comment by luca-gr4vy** [comment]
Hey @douglaseggleton I realized updating to android `1.7.4` doesn't work as it requires some new arguments to be passed to the `gr4vySDK.launch` function (`connectionOptions` and some new `cartItems` props). I'll pick up this new ticket soon https://gr4vy.atlassian.net/browse/TA-7501

**Comment by douglaseggleton** [comment]
> https://gr4vy.atlassian.net/browse/TA-7501

👍🏻 This ticket would probably duplicate some of that effort https://gr4vy.atlassian.net/browse/TA-7176

**Comment by luca-gr4vy** [comment]
hey @douglaseggleton, I think this won't be neede when https://github.com/gr4vy/gr4vy-react-native/pull/32 is merged. It's doing the same upgrade and applying the fixes for `cartItems, while passing `null` as `connectionOptions` for now (we have a separate ticket for that as we need to change the SDKs too https://gr4vy.atlassian.net/browse/TA-7609)

**Comment by douglaseggleton** [comment]
@luca-gr4vy advised this can be closed as the upgrade was performed in another PR.

**Pull request closed without merging**
